# Generated by Django 5.1.1 on 2024-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bobik_web_setup", "0002_bobiksitesetup_admin_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="bobiksitesetup",
            name="admin_password",
            field=models.CharField(
                default="123",
                help_text="Poczatkowe hasło administratora",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
