# Generated by Django 5.1.1 on 2024-09-10 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BobikChatParameters",
            fields=[
                (
                    "thread_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("imie_pacjenta", models.CharField(max_length=100)),
                ("jezyk_pacjenta", models.CharField(default="polski", max_length=30)),
                ("plec_pacjenta", models.CharField(default="mężczyzna", max_length=50)),
                ("wiek_pacjenta", models.PositiveSmallIntegerField(default=45)),
                ("tryb_zabiegu", models.CharField(default="planowy", max_length=50)),
                (
                    "rodzaj_zabiegu",
                    models.CharField(default="cholecystektomia", max_length=150),
                ),
            ],
        ),
    ]
