# Generated by Django 5.1.1 on 2024-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bobik_web_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bobikchatparameters",
            name="prompt_sent",
            field=models.BooleanField(default=False),
        ),
    ]
