# Generated by Django 5.1.1 on 2024-09-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bobik_web_chat", "0002_bobikchatparameters_prompt_sent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BobikChatParameters",
            new_name="BobikChat",
        ),
    ]
