# Generated by Django 5.1.1 on 2024-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bobik_prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bobikprompt",
            name="rodzaj",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "wywiad preanestetyczny"), (2, "badania przed operacją")],
                unique=True,
            ),
        ),
    ]
