# Generated by Django 5.1.1 on 2024-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bobik_setup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bobiksitesetup",
            name="admin_email",
            field=models.EmailField(default="foo@bar.pl", max_length=255),
            preserve_default=False,
        ),
    ]
